{% set name = "xtensor-io" %}
{% set version = "0.12.1" %}
{% set sha256 = "cf5242ad7df003f7c02da4d85655d7abe9bcf3e799dbd2bf4263644e7f687515" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-io/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - zlib
    - xtensor >=0.23.0,<0.24
    - cpp-filesystem >=1.3,<1.4
    - openimageio >=2.1,<2.3  # [not win]
    # Highfive 2.2's cmake misses the installation of the libdeps target
    - highfive >=2.0,<2.2
    - libsndfile >=1.0.28,<1.1
    - blosc >=1.20,<1.21
  run:
    # Xtensor, cpp-filesystem and highfive are header-only
    # They don't have a run_exports section
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - {{ pin_compatible('cpp-filesystem', max_pin='x.x') }}
    - {{ pin_compatible('highfive', max_pin='x.x') }}  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-io  # [unix]
    - test -f ${PREFIX}/include/xtensor-io/xtensor-io.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-io\xtensor-io.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-io\xtensor-ioConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-io\xtensor-ioConfigVersion.cmake (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image/NPZ input/output for xtensor, the C++ tensor algebra library
  description: This library enables loading of many image formats into xtensor/xarrays and NPZ.
  doc_url: http://xtensor-io.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-io

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
