{% set name = "xtensor-io" %}
{% set version = "0.12.8" %}
{% set sha256 = "9eb2879a0a681f61f4c2b4aec75b823b2c8223b50bb79bb06d72435d2c63e6ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor-io/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - xtensor >=0.23.8,<0.24
  run:
    # xtensor is header-only
    # it doesn't have a run_exports section
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - zlib
    - cpp-filesystem >=1.3,<1.4
    - openimageio >=2.1,<2.3  # [not win]
    # Highfive 2.2's cmake misses the installation of the libdeps target
    - highfive >=2.0,<2.2  # [not win]
    - libsndfile >=1.0.28,<1.1
    - blosc >=1.20,<2.0

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-io  # [unix]
    - test -f ${PREFIX}/include/xtensor-io/xtensor-io.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-io\xtensor-io.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-io\xtensor-ioConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-io\xtensor-ioConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor-io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image/NPZ input/output for xtensor, the C++ tensor algebra library
  description: This library enables loading of many image formats into xtensor/xarrays and NPZ.
  doc_url: http://xtensor-io.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-io

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
