{% set name = "xtensor-io" %}
{% set version = "0.8.0" %}
{% set sha256 = "b8c3a8b37e43935f1cc9ba1930dbf5c364fe3ce999b14441beeedd7927169763" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-io/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - zlib
    - xtensor >=0.20.4,<0.21
    - openimageio >=1.8.9,<1.9  # [not win]
    - highfive >=2.0,<2.1  # [not win]
    - libsndfile >=1.0.28,<1.1  # [not win]
  run:
    # Xtensor and highfive are header-only
    # They don't have a run_exports section
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - {{ pin_compatible('highfive', max_pin='x.x') }}  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-io  # [unix]
    - test -f ${PREFIX}/include/xtensor-io/xtensor-io.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-io/xtensor-ioConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-io\xtensor-io.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-ioConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-ioConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image/NPZ input/output for xtensor, the C++ tensor algebra library
  description: This library enables loading of many image formats into xtensor/xarrays and NPZ.
  doc_url: http://xtensor-io.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-io

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
